# Generated by Django 2.0.3 on 2018-10-23 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1)])),
                ('parent_occu', models.CharField(max_length=50)),
                ('parent_income', models.CharField(max_length=50)),
                ('parent_qual', models.CharField(max_length=50)),
                ('current_cgpa', models.IntegerField()),
                ('avg_cgpa', models.IntegerField()),
                ('ssc_marks', models.IntegerField()),
                ('hsc_marks', models.IntegerField()),
                ('stu_ach', models.CharField(max_length=50)),
                ('created', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=50)),
            ],
        ),
    ]
