# Generated by Django 2.0.3 on 2018-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_cgpa',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc_marks',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_income',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_occu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_qual',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_marks',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_ach',
            field=models.CharField(default='', max_length=50),
        ),
    ]
