# Generated by Django 2.0.3 on 2018-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181024_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
