# Generated by Django 2.0.3 on 2018-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=10, default='', max_digits=12),
        ),
    ]
