# Generated by Django 2.0.3 on 2018-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181026_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('P', 'Poor')], default='G', max_length=10),
        ),
    ]
