# Generated by Django 2.0.3 on 2018-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_student_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question1',
            field=models.CharField(choices=[('E1', 'Excellent'), ('G1', 'Good'), ('A1', 'Average'), ('P1', 'Poor')], default='G1', max_length=10),
        ),
    ]
