# Generated by Django 2.0.3 on 2018-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_student_question1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avg_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hsc_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_income',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_occu',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_qual',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ssc_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_ach',
        ),
        migrations.AddField(
            model_name='student',
            name='question2',
            field=models.CharField(choices=[('E2', 'Excellent'), ('G2', 'Good'), ('A2', 'Average'), ('P2', 'Poor')], default='G2', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='question3',
            field=models.CharField(choices=[('E3', 'Excellent'), ('G3', 'Good'), ('A3', 'Average'), ('P3', 'Poor')], default='G3', max_length=10),
        ),
    ]
